### ISSUE TITLE
Wold Map Filter - Jasmine

### ISSUE THREAD

**Issue by singh-karanpal** [UBC-MDS/DSCI_532_group_201_milestone3_4_natural_disaster#13]
@jasmineqyj Can you please check if we can add decade level drop down on world map?

The expectation from filter:
It may be used in place of slider bar (as in Python Dash App). So, if we select any year World Map should reflect those metrics only.

**Comment by jasmineqyj** [comment]
Hi @singh-karanpal ,

I have switched to the `sf` package in R and `.geojson` data to draw the map so that the dataset and the plot will have much much smaller sizes than the `geom_polygon` method. However, even with the `sf` method, the dataset for decade-level drop down is already `635kb`, without adding any interactivity. This won't pass the Iframe API size requirement. 

Right now, it seems like the only solution is to include just 1 year or aggregated data on map with basic tooltips, do you have any other idea how we could add interactivity to the map?

**Comment by singh-karanpal** [comment]
@jasmineqyj 

It looks like, a drawback of the RDash and GGplotly framework. Nothing much we can do then. We won't be aggregating data of just 1 year, that would not be the right thing to do!. We will keep it the way it is and will address this as a shortcoming of using this framework!

**Comment by jasmineqyj** [comment]
Updated map.
